function javaleague(){var U='',Cb='" for "gwt:onLoadErrorFn"',Ab='" for "gwt:onPropertyErrorFn"',nb='"><\/script>',cb='#',Kb='&',tc='.cache.html',eb='/',qb='//',bc='07093FA3A3087C6006AB7448BB5A7597',dc='2CA1A54EC711C3BCB2D622D9115F0196',fc='332C35DBBC75606B16E2C6016F935B9E',gc='5AF72172ED96F11EC43D0CD5C01F467D',hc='5FCFCC5F87CEAADFA6222FEB5CB364B7',ic='8C915D25F846CB961F0A450BA39239D9',jc='910EB0AD826D1AF659213647C78CF927',sc=':',ub='::',Mb=';',Gc='<script defer="defer">javaleague.onInjectionDone(\'javaleague\')<\/script>',mb='<script id="',xb='=',db='?',kc='A24B75B06E47AA9A9E49F8B14E9498D3',lc='A49356AAA55980D8A7AD89A24CF0D8E9',mc='A719709ABBAA3AA60531D736FA6F7728',zb='Bad handler "',nc='C264DF77D565C3FDA7289ED950264D07',oc='CCE5F3D8CB743507E5E7F0457B2B522E',pc='D4764EC03C25C980C5C700F64F6D7820',Fc='DOMContentLoaded',qc='E57EA726502C3B0A6B343AC81FB38B88',rc='F0839E57A4EB3EE003FBAF30C7F217B4',Lb='GWT_LOCALE=',ob='SCRIPT',Pb='Unexpected exception in locale detection, using default: ',Ob='_',Nb='__gwt_Locale',lb='__gwt_marker_javaleague',pb='base',hb='baseUrl',Y='begin',X='bootstrap',gb='clear.cache.gif',wb='content',Cc='css/bootstrap-datetimepicker.min.css',Bc='css/bootstrap.min.css',Ac='css/font-awesome.min.css',Ec='css/summernote-bs3.min.css',Dc='css/summernote.min.css',ec='default',cc='en',bb='end',Ib='es',Xb='gecko',Yb='gecko1_8',Z='gwt.codesvr=',$='gwt.hosted=',_='gwt.hybrid',uc='gwt/standard/standard.css',Bb='gwt:onLoadErrorFn',yb='gwt:onPropertyErrorFn',vb='gwt:property',zc='head',_b='hosted.html?javaleague',yc='href',Ub='ie10',Wb='ie8',Vb='ie9',Db='iframe',fb='img',V='javaleague',jb='javaleague.nocache.js',tb='javaleague::',Eb="javascript:''",vc='link',$b='loadExternalRefs',Hb='locale',Jb='locale=',rb='meta',Gb='moduleRequested',ab='moduleStartup',Tb='msie',sb='name',Fb='position:absolute;width:0;height:0;border:none',wc='rel',Sb='safari',ib='script',ac='selectingPermutation',W='startup',xc='stylesheet',kb='undefined',Zb='unknown',Qb='user.agent',Rb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=U,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:Y});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Z)!=-1||(c.indexOf($)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(_)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(V);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return M(a)}}javaleague=null;c.gwtOnLoad(C,V,t,B);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:bb})}}
function H(){function e(a){var b=a.lastIndexOf(cb);if(b==-1){b=a.length}var c=a.indexOf(db);if(c==-1){c=a.length}var d=a.lastIndexOf(eb,Math.min(c,b));return d>=0?a.substring(0,d+1):U}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(fb);b.src=a+gb;a=e(b.src)}return a}
function g(){var a=K(hb);if(a!=null){return a}return U}
function h(){var a=n.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(jb)!=-1){return e(a[b].src)}}return U}
function i(){var a;if(typeof isBodyLoaded==kb||!isBodyLoaded()){var b=lb;var c;n.write(mb+b+nb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ob){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return U}
function j(){var a=n.getElementsByTagName(pb);if(a.length>0){return a[a.length-1].href}return U}
function k(){var a=n.location;return a.href==a.protocol+qb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==U){l=h()}if(l==U){l=i()}if(l==U){l=j()}if(l==U&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(rb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(sb),g;if(f){f=f.replace(tb,U);if(f.indexOf(ub)>=0){continue}if(f==vb){g=e.getAttribute(wb);if(g){var h,i=g.indexOf(xb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=U}u[f]=h}}else if(f==yb){g=e.getAttribute(wb);if(g){try{D=eval(g)}catch(a){alert(zb+g+Ab)}}}else if(f==Bb){g=e.getAttribute(wb);if(g){try{C=eval(g)}catch(a){alert(zb+g+Cb)}}}}}}
function J(a,b){return b in v[a]}
function K(a){var b=u[a];return b==null?null:b}
function L(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function M(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var N;function O(){if(!N){N=true;var a=n.createElement(Db);a.src=Eb;a.id=V;a.style.cssText=Fb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:Gb});a.contentWindow.location.replace(t+Q)}}
w[Hb]=function(){var b=null;var c=Ib;try{if(!b){var d=location.search;var e=d.indexOf(Jb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Kb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){var h=n.cookie;var i=h.indexOf(Lb);if(i>=0){var g=h.indexOf(Mb,i);if(g<0){g=h.length}b=h.substring(i+11,g)}}if(!b){b=K(Hb)}if(!b){b=m[Nb]}if(b){c=b}while(b&&!J(Hb,b)){var j=b.lastIndexOf(Ob);if(j<0){b=null;break}b=b.substring(0,j)}}catch(a){alert(Pb+a)}m[Nb]=c;return b||Ib};v[Hb]={'default':0,en:1,es:2};w[Qb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Rb)!=-1}())return Sb;if(function(){return b.indexOf(Tb)!=-1&&n.documentMode>=10}())return Ub;if(function(){return b.indexOf(Tb)!=-1&&n.documentMode>=9}())return Vb;if(function(){return b.indexOf(Tb)!=-1&&n.documentMode>=8}())return Wb;if(function(){return b.indexOf(Xb)!=-1}())return Yb;return Zb};v[Qb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};javaleague.onScriptLoad=function(){if(N){r=true;G()}};javaleague.onInjectionDone=function(){q=true;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:$b,millis:(new Date).getTime(),type:bb});G()};I();H();var P;var Q;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(V))){m.location.reload();return}Q=_b;P=U}o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:ac});if(!F()){try{L([Ib,Yb],bc);L([cc,Ub],dc);L([ec,Wb],fc);L([ec,Vb],gc);L([ec,Ub],hc);L([Ib,Wb],ic);L([ec,Sb],jc);L([Ib,Sb],kc);L([cc,Sb],lc);L([Ib,Vb],mc);L([cc,Vb],nc);L([cc,Yb],oc);L([Ib,Ub],pc);L([cc,Wb],qc);L([ec,Yb],rc);P=A[M(Hb)][M(Qb)];var R=P.indexOf(sc);if(R!=-1){B=Number(P.substring(R+1));P=P.substring(0,R)}Q=P+tc}catch(a){return}}var S;function T(){if(!s){s=true;if(!__gwt_stylesLoaded[uc]){var a=n.createElement(vc);__gwt_stylesLoaded[uc]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+uc);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Ac]){var a=n.createElement(vc);__gwt_stylesLoaded[Ac]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Ac);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Bc]){var a=n.createElement(vc);__gwt_stylesLoaded[Bc]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Bc);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Cc]){var a=n.createElement(vc);__gwt_stylesLoaded[Cc]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Cc);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Dc]){var a=n.createElement(vc);__gwt_stylesLoaded[Dc]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Dc);n.getElementsByTagName(zc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Ec]){var a=n.createElement(vc);__gwt_stylesLoaded[Ec]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+Ec);n.getElementsByTagName(zc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(Fc,T,false)}if(S){clearInterval(S)}}}
if(n.addEventListener){n.addEventListener(Fc,function(){O();T()},false)}var S=setInterval(function(){if(/loaded|complete/.test(n.readyState)){O();T()}},50);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:bb});o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:$b,millis:(new Date).getTime(),type:Y});n.write(Gc)}
javaleague();